name: Build Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'

env:
  TAG_PREFIX: service-v

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: version
        id: version-id
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "(major)"
          minor_pattern: "(feat)"
          change_path: "service"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          tag_prefix: ${{ env.TAG_PREFIX }}

      - name: Print version
        run: |
          echo ${{ steps.version-id.outputs.version }}
          echo ${{ env.TIMESTAMP }}

      - name: Generate tag name and artifact name
        id: github-output-local
        run: |
          timestamp=$(date +'%Y-%m-%dT%H-%M-%S')
          echo "ARTIFACT_NAME=artifacts_${{ steps.version-id.outputs.version }}_$timestamp.zip" >> "$GITHUB_OUTPUT"
          echo "TAG_NAME=${{ env.TAG_PREFIX }}${{ steps.version-id.outputs.version }}" >> "$GITHUB_OUTPUT"

      - name: Create artifact
        id: create-artifact
        run: |
          sed -i "s/^HELM_VERSION=.*/HELM_VERSION=\"${{ steps.version-id.outputs.version }}\"/" ./helm/env/*/helm.conf
          zip -r ${{ steps.github-output-local.outputs.ARTIFACT_NAME }} */
          
          for dir in ./helm/env/*; do
            echo $dir
            dir_val=$(basename ${dir})
            echo "${dir_val}_${{ steps.github-output-local.outputs.ARTIFACT_NAME }}"
            zip -r "${dir_val}_${{ steps.github-output-local.outputs.ARTIFACT_NAME }}" "$dir"
          done
          
          ls -l *
          
          echo "ARTIFACTS=$(find . -type f -name "*${{ steps.github-output-local.outputs.ARTIFACT_NAME }}")" >> "$GITHUB_OUTPUT"
          tree

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(${{ steps.github-output-local.outputs.TAG_NAME }}, 'refs/tags/')
        with:
          files: ${{ steps.create-artifact.outputs.ARTIFACTS }}
          tag_name: ${{ steps.github-output-local.outputs.TAG_NAME }}
