name: Build Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'

env:
  TAG_PREFIX: service-v

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: version
        id: version-id
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "(major)"
          minor_pattern: "(feat)"
          change_path: "service"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          tag_prefix: ${{ env.TAG_PREFIX }}

      - name: Print version
        run: echo ${{ steps.version-id.outputs.version }}

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: service-v${{ steps.version-id.outputs.version }}

      - name: Create Release
        uses: actions/create-release@v1
        if: "steps.checkTag.outputs.exists == 'false'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_PREFIX }}${{ steps.version-id.outputs.version }}
          release_name: ${{ env.TAG_PREFIX }}${{ steps.version-id.outputs.version }}
          draft: false
          prerelease: false
